language: ruby
rvm:
  - 2.4.1
  - 2.3.3
  - 2.2
  - 2.1
before_install:
  - wget -qO- 'https://github.com/antirez/redis/archive/3.2.10.tar.gz' | tar -xzC /tmp
  - make -j -C /tmp/redis-3.2.10 INSTALL_BIN=/tmp/redis-3.2.10 install
  - cd /tmp/redis-3.2.10/src && ./redis-server > /dev/null 2>&1 &
